apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    appname: busybox_app1
  name: busybox-pvc-2
  namespace: busybox-workloads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: rook-ceph-block
